<?xml version="1.0" encoding="utf-8"?><Database Name="AlarmClock" Class="AlarmDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Soda;Initial Catalog=AlarmClock;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AlarmClockConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AlarmDetails" Member="AlarmDetails">
    <Type Name="AlarmDetail">
      <Column Name="AlarmNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AlarmText" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="AlarmDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Monday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tuesday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Wednesday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Thursday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Friday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Saturday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sunday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Snooze" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SnoozeInterval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VisualAlarm" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AudibleAlarm" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VolumeLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoundNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Blinking" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Vibrate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Flashlight" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="email1" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="email2" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="email3" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
    </Type>
  </Table>
</Database>