'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.544
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


'
'This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
'
Namespace UserServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="UserServiceReference.IUser")>  _
    Public Interface IUser
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IUser/CreateUser", ReplyAction:="http://tempuri.org/IUser/CreateUserResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BeginCreateUser(ByVal request As UserServiceReference.CreateUserRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndCreateUser(ByVal result As System.IAsyncResult) As UserServiceReference.CreateUserResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IUser/ReturnUsers", ReplyAction:="http://tempuri.org/IUser/ReturnUsersResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BeginReturnUsers(ByVal request As UserServiceReference.ReturnUsersRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndReturnUsers(ByVal result As System.IAsyncResult) As UserServiceReference.ReturnUsersResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IUser/ReturnUserList", ReplyAction:="http://tempuri.org/IUser/ReturnUserListResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BeginReturnUserList(ByVal request As UserServiceReference.ReturnUserListRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndReturnUserList(ByVal result As System.IAsyncResult) As UserServiceReference.ReturnUserListResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CreateUser", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CreateUserRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public uname As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public email As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public phone As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal uname As String, ByVal email As String, ByVal phone As String)
            MyBase.New
            Me.uname = uname
            Me.email = email
            Me.phone = phone
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CreateUserResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CreateUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CreateUserResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CreateUserResult As Integer)
            MyBase.New
            Me.CreateUserResult = CreateUserResult
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/WcfService1")>  _
    Partial Public Class User
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private emailField As String
        
        Private phoneNumberField As String
        
        Private userNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
                Me.RaisePropertyChanged("Email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property PhoneNumber() As String
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
                Me.RaisePropertyChanged("PhoneNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("UserName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ReturnUsers", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ReturnUsersRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ReturnUsersResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ReturnUsersResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public ReturnUsersResult As UserServiceReference.ArrayOfXElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ReturnUsersResult As UserServiceReference.ArrayOfXElement)
            MyBase.New
            Me.ReturnUsersResult = ReturnUsersResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ReturnUserList", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ReturnUserListRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ReturnUserListResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ReturnUserListResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/WcfService1")>  _
        Public ReturnUserListResult() As User
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ReturnUserListResult() As User)
            MyBase.New
            Me.ReturnUserListResult = ReturnUserListResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IUserChannel
        Inherits UserServiceReference.IUser, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CreateUserCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Integer
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ReturnUsersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As UserServiceReference.ArrayOfXElement
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),UserServiceReference.ArrayOfXElement)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ReturnUserListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As User()
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),User())
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UserClient
        Inherits System.ServiceModel.ClientBase(Of UserServiceReference.IUser)
        Implements UserServiceReference.IUser
        
        Private onBeginCreateUserDelegate As BeginOperationDelegate
        
        Private onEndCreateUserDelegate As EndOperationDelegate
        
        Private onCreateUserCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginReturnUsersDelegate As BeginOperationDelegate
        
        Private onEndReturnUsersDelegate As EndOperationDelegate
        
        Private onReturnUsersCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginReturnUserListDelegate As BeginOperationDelegate
        
        Private onEndReturnUserListDelegate As EndOperationDelegate
        
        Private onReturnUserListCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event CreateUserCompleted As System.EventHandler(Of CreateUserCompletedEventArgs)
        
        Public Event ReturnUsersCompleted As System.EventHandler(Of ReturnUsersCompletedEventArgs)
        
        Public Event ReturnUserListCompleted As System.EventHandler(Of ReturnUserListCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserServiceReference_IUser_BeginCreateUser(ByVal request As UserServiceReference.CreateUserRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserServiceReference.IUser.BeginCreateUser
            Return MyBase.Channel.BeginCreateUser(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginCreateUser(ByVal uname As String, ByVal email As String, ByVal phone As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As UserServiceReference.CreateUserRequest = New UserServiceReference.CreateUserRequest()
            inValue.uname = uname
            inValue.email = email
            inValue.phone = phone
            Return CType(Me,UserServiceReference.IUser).BeginCreateUser(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserServiceReference_IUser_EndCreateUser(ByVal result As System.IAsyncResult) As UserServiceReference.CreateUserResponse Implements UserServiceReference.IUser.EndCreateUser
            Return MyBase.Channel.EndCreateUser(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndCreateUser(ByVal result As System.IAsyncResult) As Integer
            Dim retVal As UserServiceReference.CreateUserResponse = CType(Me,UserServiceReference.IUser).EndCreateUser(result)
            Return retVal.CreateUserResult
        End Function
        
        Private Function OnBeginCreateUser(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim uname As String = CType(inValues(0),String)
            Dim email As String = CType(inValues(1),String)
            Dim phone As String = CType(inValues(2),String)
            Return Me.BeginCreateUser(uname, email, phone, callback, asyncState)
        End Function
        
        Private Function OnEndCreateUser(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Integer = Me.EndCreateUser(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnCreateUserCompleted(ByVal state As Object)
            If (Not (Me.CreateUserCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CreateUserCompleted(Me, New CreateUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CreateUserAsync(ByVal uname As String, ByVal email As String, ByVal phone As String)
            Me.CreateUserAsync(uname, email, phone, Nothing)
        End Sub
        
        Public Overloads Sub CreateUserAsync(ByVal uname As String, ByVal email As String, ByVal phone As String, ByVal userState As Object)
            If (Me.onBeginCreateUserDelegate Is Nothing) Then
                Me.onBeginCreateUserDelegate = AddressOf Me.OnBeginCreateUser
            End If
            If (Me.onEndCreateUserDelegate Is Nothing) Then
                Me.onEndCreateUserDelegate = AddressOf Me.OnEndCreateUser
            End If
            If (Me.onCreateUserCompletedDelegate Is Nothing) Then
                Me.onCreateUserCompletedDelegate = AddressOf Me.OnCreateUserCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCreateUserDelegate, New Object() {uname, email, phone}, Me.onEndCreateUserDelegate, Me.onCreateUserCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserServiceReference_IUser_BeginReturnUsers(ByVal request As UserServiceReference.ReturnUsersRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserServiceReference.IUser.BeginReturnUsers
            Return MyBase.Channel.BeginReturnUsers(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginReturnUsers(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As UserServiceReference.ReturnUsersRequest = New UserServiceReference.ReturnUsersRequest()
            Return CType(Me,UserServiceReference.IUser).BeginReturnUsers(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserServiceReference_IUser_EndReturnUsers(ByVal result As System.IAsyncResult) As UserServiceReference.ReturnUsersResponse Implements UserServiceReference.IUser.EndReturnUsers
            Return MyBase.Channel.EndReturnUsers(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndReturnUsers(ByVal result As System.IAsyncResult) As UserServiceReference.ArrayOfXElement
            Dim retVal As UserServiceReference.ReturnUsersResponse = CType(Me,UserServiceReference.IUser).EndReturnUsers(result)
            Return retVal.ReturnUsersResult
        End Function
        
        Private Function OnBeginReturnUsers(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginReturnUsers(callback, asyncState)
        End Function
        
        Private Function OnEndReturnUsers(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As UserServiceReference.ArrayOfXElement = Me.EndReturnUsers(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnReturnUsersCompleted(ByVal state As Object)
            If (Not (Me.ReturnUsersCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ReturnUsersCompleted(Me, New ReturnUsersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ReturnUsersAsync()
            Me.ReturnUsersAsync(Nothing)
        End Sub
        
        Public Overloads Sub ReturnUsersAsync(ByVal userState As Object)
            If (Me.onBeginReturnUsersDelegate Is Nothing) Then
                Me.onBeginReturnUsersDelegate = AddressOf Me.OnBeginReturnUsers
            End If
            If (Me.onEndReturnUsersDelegate Is Nothing) Then
                Me.onEndReturnUsersDelegate = AddressOf Me.OnEndReturnUsers
            End If
            If (Me.onReturnUsersCompletedDelegate Is Nothing) Then
                Me.onReturnUsersCompletedDelegate = AddressOf Me.OnReturnUsersCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginReturnUsersDelegate, Nothing, Me.onEndReturnUsersDelegate, Me.onReturnUsersCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserServiceReference_IUser_BeginReturnUserList(ByVal request As UserServiceReference.ReturnUserListRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserServiceReference.IUser.BeginReturnUserList
            Return MyBase.Channel.BeginReturnUserList(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginReturnUserList(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As UserServiceReference.ReturnUserListRequest = New UserServiceReference.ReturnUserListRequest()
            Return CType(Me,UserServiceReference.IUser).BeginReturnUserList(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UserServiceReference_IUser_EndReturnUserList(ByVal result As System.IAsyncResult) As UserServiceReference.ReturnUserListResponse Implements UserServiceReference.IUser.EndReturnUserList
            Return MyBase.Channel.EndReturnUserList(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndReturnUserList(ByVal result As System.IAsyncResult) As User()
            Dim retVal As UserServiceReference.ReturnUserListResponse = CType(Me,UserServiceReference.IUser).EndReturnUserList(result)
            Return retVal.ReturnUserListResult
        End Function
        
        Private Function OnBeginReturnUserList(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginReturnUserList(callback, asyncState)
        End Function
        
        Private Function OnEndReturnUserList(ByVal result As System.IAsyncResult) As Object()
            Dim retVal() As User = Me.EndReturnUserList(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnReturnUserListCompleted(ByVal state As Object)
            If (Not (Me.ReturnUserListCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent ReturnUserListCompleted(Me, New ReturnUserListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub ReturnUserListAsync()
            Me.ReturnUserListAsync(Nothing)
        End Sub
        
        Public Overloads Sub ReturnUserListAsync(ByVal userState As Object)
            If (Me.onBeginReturnUserListDelegate Is Nothing) Then
                Me.onBeginReturnUserListDelegate = AddressOf Me.OnBeginReturnUserList
            End If
            If (Me.onEndReturnUserListDelegate Is Nothing) Then
                Me.onEndReturnUserListDelegate = AddressOf Me.OnEndReturnUserList
            End If
            If (Me.onReturnUserListCompletedDelegate Is Nothing) Then
                Me.onReturnUserListCompletedDelegate = AddressOf Me.OnReturnUserListCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginReturnUserListDelegate, Nothing, Me.onEndReturnUserListDelegate, Me.onReturnUserListCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As UserServiceReference.IUser
            Return New UserClientChannel(Me)
        End Function
        
        Private Class UserClientChannel
            Inherits ChannelBase(Of UserServiceReference.IUser)
            Implements UserServiceReference.IUser
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of UserServiceReference.IUser))
                MyBase.New(client)
            End Sub
            
            Public Function BeginCreateUser(ByVal request As UserServiceReference.CreateUserRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserServiceReference.IUser.BeginCreateUser
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("CreateUser", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndCreateUser(ByVal result As System.IAsyncResult) As UserServiceReference.CreateUserResponse Implements UserServiceReference.IUser.EndCreateUser
                Dim _args((0) - 1) As Object
                Dim _result As UserServiceReference.CreateUserResponse = CType(MyBase.EndInvoke("CreateUser", _args, result),UserServiceReference.CreateUserResponse)
                Return _result
            End Function
            
            Public Function BeginReturnUsers(ByVal request As UserServiceReference.ReturnUsersRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserServiceReference.IUser.BeginReturnUsers
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("ReturnUsers", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndReturnUsers(ByVal result As System.IAsyncResult) As UserServiceReference.ReturnUsersResponse Implements UserServiceReference.IUser.EndReturnUsers
                Dim _args((0) - 1) As Object
                Dim _result As UserServiceReference.ReturnUsersResponse = CType(MyBase.EndInvoke("ReturnUsers", _args, result),UserServiceReference.ReturnUsersResponse)
                Return _result
            End Function
            
            Public Function BeginReturnUserList(ByVal request As UserServiceReference.ReturnUserListRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements UserServiceReference.IUser.BeginReturnUserList
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("ReturnUserList", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndReturnUserList(ByVal result As System.IAsyncResult) As UserServiceReference.ReturnUserListResponse Implements UserServiceReference.IUser.EndReturnUserList
                Dim _args((0) - 1) As Object
                Dim _result As UserServiceReference.ReturnUserListResponse = CType(MyBase.EndInvoke("ReturnUserList", _args, result),UserServiceReference.ReturnUserListResponse)
                Return _result
            End Function
        End Class
    End Class
    
    <System.Xml.Serialization.XmlSchemaProviderAttribute(Nothing, IsAny:=true),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Silverlight.Phone.ServiceReference", "3.7.0.0")>  _
    Partial Public Class ArrayOfXElement
        Inherits Object
        Implements System.Xml.Serialization.IXmlSerializable
        
        Private nodesList As System.Collections.Generic.List(Of System.Xml.Linq.XElement) = New System.Collections.Generic.List(Of System.Xml.Linq.XElement)()
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Overridable ReadOnly Property Nodes() As System.Collections.Generic.List(Of System.Xml.Linq.XElement)
            Get
                Return Me.nodesList
            End Get
        End Property
        
        Public Overridable Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
            Throw New System.NotImplementedException()
        End Function
        
        Public Overridable Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
            Dim e As System.Collections.Generic.IEnumerator(Of System.Xml.Linq.XElement) = nodesList.GetEnumerator

            Do While e.MoveNext
                CType(e.Current,System.Xml.Serialization.IXmlSerializable).WriteXml(writer)

            Loop
        End Sub
        
        Public Overridable Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml

            Do While (reader.NodeType <> System.Xml.XmlNodeType.EndElement)
                If (reader.NodeType = System.Xml.XmlNodeType.Element) Then
                    Dim elem As System.Xml.Linq.XElement = New System.Xml.Linq.XElement("default")
                    CType(elem,System.Xml.Serialization.IXmlSerializable).ReadXml(reader)
                    Nodes.Add(elem)
                Else
                    reader.Skip
                End If

            Loop
        End Sub
    End Class
End Namespace
